mongock:
    migration-scan-package: VSDS
springdoc:
    swagger-ui:
        path: /v1/swagger
ldes-server:
    host-name: "http://localhost:8080"
    retention-cron: "*/20 * * * * *"
    ldes-server.deletion-cron: "*/20 * * * * *"
    ldes-server.compaction-duration: "PT20M"
    ldes-server.compaction-cron: "*/20 * * * * *"
management:
    tracing:
        enabled: false
spring:
  data:
    mongodb:
        database: odala
        host: ldes-mongodb
        port: 27017
        auto-index-creation: true